---
name: Recorridos
locale: es
type: learning
beta: false
teacher_info: ''
language: javascript
id_format: "%05d"
order:
- 3
- 5
- 8
- 16
- 17
- 9
- 18
- 19
- 13
- 6
- 7
- 10
- 14
- 15
private: false
